### ISSUE TITLE
Which client version is this suitable for?

### ISSUE THREAD

**Issue by xmflswood** [vans163/linLauncher#1]
I am looking for launcher source code suitable for 3.5, 3.63, and 3.81 clients. Do you have any relevant materials?
I found that:
https://github.com/l1j/l1jlogin

but i need source code.
That seem suite for V2: https://github.com/l1j/Launcher

**Comment by xmflswood** [comment]
It's very difficult to find the materials. I've noticed that your account has been active recently and I'm really looking forward to your reply.
Thanks！

**Comment by vans163** [comment]
Hum.. what server are you trying to run on?

I haven't touched this in a while but could possibly update it with more info.

It looks like it just launches the gameclient with some cmdline args and sets a flag in the config file to start game in windowed mode.

Are those clients the new large resolution clients? If possible I would run one of them and see what it passes as the cmdline args, if anything.

**Comment by xmflswood** [comment]
Thank you for your reply. I am still learning about the old client launcher technology (not the new large resolution clients), such as 3.63 and 3.81.

I was originally hoping to obtain the source code for this project at https://github.com/LineagePLUS/L1Login/tree/Login_363.

But now I've realized that whether or not I can get the source code is not important (it might be difficult to obtain the source code).

For example, in this project:

encode/encode.exe is used to generate an encrypted configuration file cfg for login/login.exe to use.
login/login.exe is also customized, and it probably uses injection methods to decrypt and parse key information from cfg (such as server IP, packet encryption keys, etc.).
So, in addition to these ready-made "login + encode" projects, I can also learn injection methods to achieve the same goal.（
Although it's very challenging for me, I have no experience at all.）

Thanks again for your reply!

**Comment by xmflswood** [comment]
In short, I originally thought that both the login and encode came from the same source code. Later, I realized that they are based on the same principles but can be implemented in a variety of ways.

**Comment by vans163** [comment]
> Thank you for your reply. I am still learning about the old client launcher technology (not the new large resolution clients), such as 3.63 and 3.81.
> 
> I was originally hoping to obtain the source code for this project at https://github.com/LineagePLUS/L1Login/tree/Login_363.
> 
> But now I've realized that whether or not I can get the source code is not important (it might be difficult to obtain the source code).
> 
> For example, in this project:
> 
> encode/encode.exe is used to generate an encrypted configuration file cfg for login/login.exe to use. login/login.exe is also customized, and it probably uses injection methods to decrypt and parse key information from cfg (such as server IP, packet encryption keys, etc.). So, in addition to these ready-made "login + encode" projects, I can also learn injection methods to achieve the same goal.（ Although it's very challenging for me, I have no experience at all.）
> 
> Thanks again for your reply!

This seems to have extra encryption from when I coded this linLauncher, perhaps this is for a newer version of the client?

The original target server, Resurrection, didn't use this encryption, the cfg was plaintext.

The dllinjector is an old weapon, from a much simpler time, it has no relation to the launcher, I was using it to "debug" some stuff, nowadays its simpler to use Frida.
